"""empty message

Revision ID: 21577e96944d
Revises: 1bc6a6a50fb9
Create Date: 2024-12-15 02:06:51.820481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21577e96944d'
down_revision = '1bc6a6a50fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
